Add New Message Indicators
Meta-Games-Biz/Kings-Corner pull request #141
Opened 2021-09-23 00:51 UTC by mrrosoff

fixes #112

Try Me!

2021-10-03 18:55 UTC, matthewfernst requested changes
Sooooo the cache is all screwy at least for my build. I got a friend request from Miranda and when I went to accept it the cache failed with the new apollo?? Some about selfLookup is self depreciating?  Not sure!

2021-10-03 19:18 UTC, mrrosoff commented
@matthewfernst Are you talking about production? Because production cache is indeed down.

2021-10-03 21:55 UTC, matthewfernst commented
@mrrosoff Basically my project structure was all messed up so I deleted node_modules and package-lock.json and did npm install and some weird directory that needed to be renamed and it was acting wacky after npm start. Maybe Discord sometime and look?

2021-10-04 02:30 UTC, matthewfernst approved these changes

2021-10-04 02:30 UTC, merged