Shop hookup
Meta-Games-Biz/Kings-Corner pull request #40
Opened 2021-05-10 17:59 UTC by matthewfernst

shop hooked up 👍

2021-05-10 18:12 UTC, mrrosoff requested changes
Nice, couple tweaks needed

2021-05-10 18:12 UTC, mrrosoff commented on client/components/App/Pages/Collection.jsx
> +	console.log(props.data.selfLookup.items)
Delete for meeee

2021-05-10 18:12 UTC, mrrosoff commented on client/components/App/Pages/Collection.jsx
> +									showCheckMark={props.data.selfLookup.items.map(item => item.name).includes(item.name)}
Plz auto format :)

2021-05-10 18:12 UTC, mrrosoff commented on client/components/App/Pages/Shop.jsx
> +	const [confirmPurchase, setConfirmPurchase] = useState(false);
Ok but what if I click one but there are many, does it show the new UI for all of them?

2021-05-10 18:12 UTC, mrrosoff commented on client/graphql/mutation.js
> +				description
Add thumbnail here!

2021-05-10 18:12 UTC, mrrosoff commented on server/gqlTypes/mutation.js
> +			{ _id: context.userId },
You are subtracting money twice, why?

2021-05-10 21:03 UTC, mrrosoff commented
Closes #4

2021-05-11 02:21 UTC, matthewfernst commented on client/components/App/Pages/Shop.jsx
> +	const [confirmPurchase, setConfirmPurchase] = useState(false);
fixed in recent push

2021-05-11 02:30 UTC, mrrosoff requested changes

2021-05-11 03:16 UTC, mrrosoff approved these changes

2021-05-11 03:17 UTC, merged