Missions
Meta-Games-Biz/Kings-Corner pull request #55
Opened 2021-05-14 22:56 UTC by matthewfernst

mission

2021-05-14 22:58 UTC, mrrosoff submitted a review, later dismissed

2021-05-15 19:39 UTC, mrrosoff requested changes
Does this work? Will have time to test more thoroughly later. Heres a couple things to fix.

2021-05-15 19:39 UTC, mrrosoff commented on client/components/App/HeaderBar/Missions.jsx
> +const useStyles = makeStyles((theme) => ({}));
If we dont use this can we remove?

2021-05-15 19:39 UTC, mrrosoff commented on client/components/App/HeaderBar/Missions.jsx
> +	const { loading, error, data } = useQuery(GetHeaderNotifications);
Can we use a separate query for missions?

2021-05-15 19:39 UTC, mrrosoff commented on schema.graphql
> +	missions: [Mission!]!
Why do we have this?

2021-05-15 19:39 UTC, mrrosoff commented on server/utils.js
>  export const checkInMyFriends = async (context, friendUsername) => {
This method is async, can we make sure we await all calls?

2021-05-15 20:39 UTC, matthewfernst commented on schema.graphql
> +	missions: [Mission!]!
Miss typed but it's gone. Not needed.

2021-05-15 20:40 UTC, matthewfernst commented on server/utils.js
>  export const checkInMyFriends = async (context, friendUsername) => {
updated all with await.

2021-05-15 20:42 UTC, matthewfernst commented on client/components/App/HeaderBar/Missions.jsx
> +	const { loading, error, data } = useQuery(GetHeaderNotifications);
Is there a downside to using this one?

2021-05-16 15:39 UTC, mrrosoff commented
fixes #6

2021-05-16 15:40 UTC, mrrosoff approved these changes

2021-05-16 16:31 UTC, merged